version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 258422
      POSTGRES_DB: mydatabase
      JWT_SECRET: Shivendra

    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  api:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:258422@db:5432/mydatabase
      JWT_SECRET: your_jwt_secret
    ports:
      - "3000:3000"

volumes:
  db_data:
